version: '3.8'

services:
  php-backend:
    container_name: php-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - .:/app
    env_file:
      - .env
